### ISSUE TITLE
Tests fail when building on Nix sandbox with GHC 9.4

### ISSUE THREAD

**Issue by eldritch-cookie** [brandonchinn178/tasty-autocollect#54]
[tasty-autocollect-tests-fail.log](https://github.com/brandonchinn178/tasty-autocollect/files/14812041/tasty-autocollect-tests-fail.log)
this seems to be caused by the runghc function though i don't know why.
I will probably contribute a "fix" on nixpkgs but i wanted to have an issue and to inform this problem because i am uncertain if something is wrong in your test suite or nixpkgs.

**Comment by brandonchinn178** [comment]
Yes  this test suite runs integration tests, which I've seen Nix have problems with. With cabal, you usually need to run the tests with `cabal exec cabal test`, not just `cabal test`. Nix probably needs the equivalent.

If possible, I would just skip the test suite in Nix

**Comment by eldritch-cookie** [comment]
> If possible, I would just skip the test suite in Nix

https://github.com/NixOS/nixpkgs/pull/300237 done
